export const FETCH_POPULAR_REPOS = 'FETCH_POPULAR_REPOS'
export const FETCH_REPO_BY_USER = 'FETCH_REPO_BY_USER'
export const FETCH_USER = 'FETCH_USER'

export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const USER_NOT_FOUND = 'USER_NOT_FOUND'
export const REQUEST_REPOS_BY_LANG = 'REQUEST_REPOS_BY_LANG'
export const RECEIVE_REPOS_BY_LANG = 'RECEIVE_REPOS_BY_LANG'
